# GitHub Actions for pgSQL HTTP
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:
    name: PG ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container:
      image: pgxn/pgxn-tools
    strategy:
      fail-fast: false
      matrix:
        pg: [15, 16, 17, 18, 19]

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 9080:80

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v6

    - name: 'Start PostgreSQL ${{ matrix.pg }}'
      run: pg-start ${{ matrix.pg }}

    - name: 'Install libcurl'
      run: |
        apt-get update
        apt-get -y install libcurl4-gnutls-dev


    - name: 'Build & Install'
      run: |
        export PG_CFLAGS=-Werror
        make with_llvm=no && make install

    - name: 'Test'
      run: PGUSER=postgres make installcheck || (cat regression.diffs && false)
